CREATE TABLE IF NOT EXISTS MOVIES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    director VARCHAR(100) NOT NULL,
    category VARCHAR(100)  NOT NULL,
    release_date DATE NOT NULL
); 